# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    fromEmail: 'support@f5test.in.ua'
    fromName: 'Support'

services:
    app.mailer:
        class: AppBundle\Service\Mailer
        arguments: ["%fromEmail%", "%fromName%"]
